// Code generated by "stringer -type=TblSeq"; DO NOT EDIT.

package schema

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SeqTblInformationSchema-0]
	_ = x[SeqTblTable-65535]
}

const (
	_TblSeq_name_0 = "SeqTblInformationSchema"
	_TblSeq_name_1 = "SeqTblTable"
)

func (i TblSeq) String() string {
	switch {
	case i == 0:
		return _TblSeq_name_0
	case i == 65535:
		return _TblSeq_name_1
	default:
		return "TblSeq(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
